### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by wltjr** [racker/perigee#23]
Things that depend on this such as gophercloud do not compile against 0.0.0 tag. They do compile against current sources. It would be nice if there could be a new tag 0.1.0 maybe. That way we can specify a version rather than having to pull sources. Its better for packaging, such as gentoo ebuilds, where I presently have to use the 9999/live source version instead of a tagged version. Much rather use a tagged version, so I can depend on that rather than 9999 ebuild. That you have to re-emerge to re-fetch current source. Good for development, not good for a package that others will use. Thanks!

https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-go/gophercloud/gophercloud-1.0.0.ebuild

**Comment by mburns** [comment]
It is probably too late, but I've just cut a `v0.1.0` tag for `HEAD`. Sorry this ticket got lost in the shuffle, @wltjr.

https://github.com/racker/perigee/releases/tag/v0.1.0

**Comment by wltjr** [comment]
Oh no problem, thanks for the tag. 👍  I was closing more because some do not like to version Go projects because Go is anti versioning. Some others have been opposed to harmless tags.

**Comment by sam-falvo** [comment]
I feel bad; I had no idea this issue was open, and to think it's been open for almost a year!  Thanks @mburns for cutting the tag.  Notification fail.  :(

**Comment by wltjr** [comment]
No need to feel bad, it was VERY minor. Plus I opened another similar request after this one and was denied [mitchellh/mapstructure/issues/39](https://github.com/mitchellh/mapstructure/issues/39). These are just dependencies of Rackspace rack command, which I was packaging for Gentoo. [ebuild](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/app-admin/rack). The slots were so I could pull in the right stuff and have it build. I had some issues where one required a slotted version and others live or vice versa. But I haven't been using rack, so its pretty moot. I have other things ingored in Gentoo for much longer that are actual fixes and other things. This was just over tag, but clearly you all are on it normally thus taking it to heart. Its all good!
